version: '3.8'
services:
  db-stats:
    restart: always
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    environment:
      - DEBUG=true
      - POSTGRES_DB=vssstats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5