server:
  port: 8099

springdoc:
  api-docs:
    path: /api-docs

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/vssstats
    username: postgres
    password: postgres
